apiVersion: v1
kind: Service
metadata:
  name: mongo
  namespace: crawler-platform
spec:
  selector:
    app: mongo
  ports:
    - port: 27017

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: crawler-platform
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:7
          ports:
            - containerPort: 27017
          resources:
            limits:
              cpu: 500m
              memory: 512Mi
            requests:
              cpu: 100m
              memory: 256Mi
