apiVersion: v1
kind: Service
metadata:
  name: postgres
  namespace: crawler-platform
spec:
  selector:
    app: postgres
  ports:
    - port: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: crawler-platform
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              value: crawler
            - name: POSTGRES_PASSWORD
              value: crawler
            - name: POSTGRES_DB
              value: crawler
          ports:
            - containerPort: 5432
          resources:
            limits:
              cpu: "1"
              memory: 512Mi
            requests:
              cpu: 250m
              memory: 256Mi
