ALTER TABLE scheduled_tasks
ADD COLUMN IF NOT EXISTS retry_limit INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS retry_delay_seconds INTEGER NOT NULL DEFAULT 0;

ALTER TABLE executions
ADD COLUMN IF NOT EXISTS retry_limit INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS retry_count INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS retry_delay_seconds INTEGER NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS retry_of_execution_id TEXT NULL REFERENCES executions(id),
ADD COLUMN IF NOT EXISTS retried_at TIMESTAMPTZ NULL;
