ALTER TABLE executions
  ADD COLUMN IF NOT EXISTS cpu_cores DOUBLE PRECISION NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS memory_mb INTEGER NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS timeout_seconds INTEGER NOT NULL DEFAULT 0;
